# Site settings
title: Fufu - a future friendly front-end style guide 
description: > # this means to ignore newlines until "baseurl:"
  A future friendly front-end style guide that even caters for feature phones.
baseurl: /fufu

# Build settings
markdown: kramdown

collections:
  atoms:
    output: true
  molecules:
    output: true
  organisms:
    output: true
  ecosystems:
    output: true

sass:
    style: :compressed
    